# Generated by Django 4.1.2 on 2024-03-19 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(unique=True)),
                ('category', models.CharField(default='', max_length=128)),
                ('name', models.CharField(default='', max_length=128)),
                ('unit', models.CharField(default='', max_length=16)),
                ('rule', models.IntegerField(unique=True)),
                ('supplier', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(unique=True)),
                ('date', models.DateField(default=datetime.datetime(2, 1, 1, 0, 0))),
                ('point_id', models.IntegerField(unique=True)),
                ('item_id', models.IntegerField(unique=True)),
                ('quantity', models.IntegerField(unique=True)),
                ('type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
    ]
